/*************************************************************************************************************************************
@file           Gpt.c
@version        1.0.0
@brief          AUTOSAR GPT Driver  (STM32F103X6).
@details        AUTOSAR 4.4.0 GPT module implementation. Contains the internal logic for
                driver initialization, timer channel start/stop operations, timeout value
                loading, notification handling, and status management based on the
                configuration set generated by the GPT configuration tool.
@author         abdallah mohamed sedik
*************************************************************************************************************************************/

/*************************************************************************************************************************************
Project         : AUTOSAR 4.4.0 MCAL
Platform        : ARM Cortex-M3
MCU             : STM32F103X6
Package         : LQFP48
Module          : GPT
Autosar Version : 4.4.0
Vendor Release  : R24-11
Autosar Revision: ASR_REL_4_4_REV_0000
Sw Version      : 1.0.0
*************************************************************************************************************************************/
#include  "Gpt.h"
#include "Reg_eSys_Rcc.h"



const Gpt_ConfigType Gpt_Config[]=
{
		{GPT_CHANNEL_TIM2,2 ,GPT_MODE_ONESHOT},
		{GPT_CHANNEL_TIM3,4 ,GPT_MODE_ONESHOT}
};

static Gpt_RegisterType* const Gpt_ChannelToReg[GPT_CHANNEL_MAX] =
{
		GPT2_REG,   /* [GPT_CHANNEL_TIM2] */
		GPT3_REG    /* [GPT_CHANNEL_TIM3] */
};
static const uint32 Gpt_ChannelToClockBit[GPT_CHANNEL_MAX] =
{
		RCC_APB1ENR_TIM2EN,   /* [GPT_CHANNEL_TIM2] */
		RCC_APB1ENR_TIM3EN    /* [GPT_CHANNEL_TIM3] */
};

void Gpt_Init(const Gpt_ConfigType* configPtr)
{

	if((configPtr->channelId >= GPT_CHANNEL_MAX) ||(configPtr ->prescaler <=0 ))
	{
		return;
	}
	else
	{
		Gpt_RegisterType* timReg = Gpt_ChannelToReg[configPtr->channelId];
		/* 1. Enable peripheral clock */
		RCC_REG->APB1ENR |= (1<<Gpt_ChannelToClockBit[configPtr ->channelId]);
		/* 2. Set prescaler */
		timReg->PSC = configPtr ->prescaler;
		/* 3. Set counting mode    One Pulse Mode  or         contin.  */
		if (configPtr->mode == GPT_MODE_ONESHOT)
		{
			timReg->CR1 |= (1 << TIM_CR1_OPM);
		}
		else
		{
			timReg->CR1 &= ~(1 << TIM_CR1_OPM);
		}
		/* 4. Reset counter, do NOT start yet */
		timReg->CNT =0;
		timReg->CR1 &=~(1<<TIM_CR1_CEN);




	}
}
// 2. Start - يبدأ العد لحد target value معين (بالـ ticks)
void Gpt_StartTimer(Gpt_ChannelType channel, Gpt_ValueType value)
{
	/*validate input*/
	if((channel>= GPT_CHANNEL_MAX )|| (value > GPT_MAX_TIMER_VALUE))
	{
		return;
	}
	/* get register pointer*/
	Gpt_RegisterType* timReg = Gpt_ChannelToReg[channel];
	timReg->ARR =value;
	/*clear counter*/
	timReg->CNT =0;
	/*clear pending update flag*/
	timReg->SR &=~(1<<TIM_SR_UIF);
	/*activate counter*/
	timReg->CR1 |=(1<<TIM_CR1_CEN);
}

void Gpt_StopTimer(Gpt_ChannelType channel)
{	/*validate input*/
	if(channel>= GPT_CHANNEL_MAX )
	{
			return;
	}
	Gpt_RegisterType* timReg = Gpt_ChannelToReg[channel];
	/*stop the counter */
	timReg->CR1 &=~(1<<TIM_CR1_CEN);

}
Gpt_ValueType Gpt_GetTimeElapsed(Gpt_ChannelType channel)
{	/*validate input*/
	if(channel>= GPT_CHANNEL_MAX )
		{
				return 0;
		}
		Gpt_RegisterType* timReg = Gpt_ChannelToReg[channel];
		return timReg->CNT ;

}

